 version: 2.1

 jobs:
   build:
     docker:
       - image: mcr.microsoft.com/dotnet/core/sdk:3.1-buster
    
     steps:
       - checkout
       - run: 
          name: Restaurar pacotes
          command: dotnet restore Server/Censo.NET.sln
       - run:
          name: Compilar a aplicação
          command: dotnet build Server/Censo.NET.sln -c Release -o /app/build
       - run:
          name: Executar testes
          command: ASPNETCORE_ENVIRONMENT=Test && dotnet test Server/Censo.NET.sln

          